CREATE DATABASE `tarjeta`;

USE `tarjeta`;

CREATE TABLE IF NOT EXISTS CLIENT (
  dni VARCHAR(10) PRIMARY KEY,
  name VARCHAR(15) NOT NULL,
  surname VARCHAR(15) NOT NULL,
  tlf VARCHAR(12) NOT NULL,
  email VARCHAR(25) NOT NULL,
  address VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS CARD (
  id INT PRIMARY KEY AUTO_INCREMENT,
  points INT NOT NULL DEFAULT '0',
  status BOOLEAN NOT NULL DEFAULT 0,
  dni_client VARCHAR(10) NOT NULL,
  FOREIGN KEY (dni_client) REFERENCES CLIENT(dni) ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS PRICE (
  id INT PRIMARY KEY AUTO_INCREMENT,
  status BOOLEAN NOT NULL DEFAULT 0,
  requirement INT,
  lot INT,
  concept VARCHAR(254)
);

CREATE TABLE IF NOT EXISTS exchange (
  card_id INT,
  price_id INT,
  PRIMARY KEY (card_id, price_id),
  FOREIGN KEY (card_id) REFERENCES CARD(id) ON UPDATE CASCADE,
  FOREIGN KEY (price_id) REFERENCES PRICE(id) ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS PURCHASE (
  id INT PRIMARY KEY AUTO_INCREMENT,
  store_id INT NOT NULL,
  buy_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  total INT NOT NULL,
  card_id VARCHAR(10) NOT NULL,
  FOREIGN KEY (card_id) REFERENCES CARD(id) ON UPDATE CASCADE
);
